### ISSUE TITLE
CrowdIn API v1 deprecation

### ISSUE THREAD

**Issue by matusfaro** [DigitalMediaServer/crowdin-maven-plugin#1]
Version 1 will soon be deprecated as per [docs](https://support.crowdin.com/api/api-integration-setup/#deprecation_notice):

> The old API will remain fully functional until the end of 2021.

**Comment by Nadahar** [comment]
That is a big problem, but I don't have the time to look at it at the moment. I don't know how substantial the changes are, contributions are welcome.
