### ISSUE TITLE
Doesn't work with maven submodules

### ISSUE THREAD

**Issue by matusfaro** [DigitalMediaServer/crowdin-maven-plugin#2]
Within a Maven submodule, plugin cannot find `.git` folder as it checks for submodules `baseDir`.

```
An error occurred while opening project basedir with git: repository not found: /Users/matus/dev/clearflask/clearflask-i18n
```

**Comment by Nadahar** [comment]
I'm not exactly sure how to deal with that. I mean, it would probably work if the submodules were separate git repos, but that probably isn't a very common situation.

Git is used to support branches, so one option might be to disable branch support though configuration. It might be other solutions for additional configuration options that might allow the "git folder" to be specified separately, but I'd have to look into it all to really get an overview. Any suggestion as to how it could best be addressed?

**Comment by matusfaro** [comment]
> allow the "git folder" to be specified separately

This is the best solution I thought of as well.

I decided to hold off on automating and using this plugin so this is not urgent for me. I may revisit this again later and open a PR then.

**Comment by Nadahar** [comment]
Version 2.0.0 adds the possibility both to disable branches and Git altogether, and to specify an absolute or relative (to "base folder") repository path.
