### ISSUE TITLE
Unable to configure <translationFileSets>

### ISSUE THREAD

**Issue by ValentinLorand** [DigitalMediaServer/crowdin-maven-plugin#6]
Hello,
Thank you for integrating the API V2 of Crowdin in a Maven plugin !

I'm trying to integrate your plugin since the https://github.com/glandais/crowdin-maven is not working anymore.

I'm facing some difficulties to configure the plugin in order to have the exact same behavior.

Is it possible to share an working example of configuration of the plugin ?

I share you mine : 
```
<plugin>
    <groupId>org.digitalmediaserver</groupId>
    <artifactId>crowdin-maven-plugin</artifactId>
    <version>${crowdin.plugin.version}</version>
    <configuration>
        <projectId>${crowdin.project.id}</projectId>
        <crowdinServerId>${crowdin.server.id}</crowdinServerId>
        <projectName>${crowdin.project.name}</projectName>
        <disableBranches>true</disableBranches>
        <downloadFolder>${project.basedir}/target/crowdin</downloadFolder>
        <translationFileSets>
            <translationFileSet>
                <title>Test</title>
                <addComment>false</addComment>
               <languageFilesFolder>${project.basedir}/src/main/resources/i18n</languageFilesFolder>
                <baseFileName>messages.properties</baseFileName>
                <exportPattern>messages_%locale_with_underscore%.properties</exportPattern>
                <targetFileName>messages_%crowdin_code_with_underscore%.properties</targetFileName>
                <updateOption>keep_translations</updateOption>
            </translationFileSet>
        </translationFileSets>
    </configuration>
</plugin>
```

My problem is concerning `translationFileSets` which I don't really know is for what.
The download part is OK, I retrieve all the translations from Crowdin server but now I want to filter them to keep only translations that I need and copy them to a specific folder with default value in English for missing values.

Is it possible to do this with this plugin ?

Thank you,
Valentin

**Comment by Nadahar** [comment]
A working configuration can be found here: https://github.com/DigitalMediaServer/DigitalMediaServer/blob/a7bc961bcc7bed9a9addc0e6d6309b9aad16a4c2/pom.xml#L620-L681

A `translationFileSet` is a set of translated files (the "root language" file and all the localized versions). If you only have one "master" file `message.properties`, you only need one `translationFileSet`. The plugin can handle many other file sets as well, of different types. Basically, you need one `translationFileSet` for each "source" file in your Crowdin project. In the above example, you can see how this is used to also handle translation of the Windows installer files.

There's no functionality in the plugin that replaces empty values with their English counterparts. This is easily achieved with Java code instead, in fact I think the standard Java "resource bundle" functionality does this by default, as long as you have defined the correct "root" bundle. See this class for reference: https://github.com/DigitalMediaServer/DigitalMediaServer/blob/master/src/main/java/net/pms/Messages.java

There is no filtering of the files in the plugin, and I'm not sure if I fully understand what you mean. Are you thinking of some kind of pattern filtering? If you routinely want to leave out translations in a way that allows you to define it in a pattern, wouldn't it be better to delete the strings in the "root" file? Or move them to a separate source file (using a different `translationFileSet`?

**Comment by ValentinLorand** [comment]
Thanks, your example helped me a lot !

I needed to pull all the translations depending of the dependencies declared in my pom.xml. I think this feature has been lost since the original glandais project. So I reimplemented a plugin which is specific for my needs (https://github.com/ValentinLorand/crowdin-plugin)

**Comment by Nadahar** [comment]
> I needed to pull all the translations depending of the dependencies declared in my pom.xml. I think this feature has been lost since the original glandais project.

There is nothing left of the glandais source code in this plugin anymore - so yes, any functionality that I "don't understand" has been lost. I still don't understand what it is that you're after. Is this related to some multi-POM setup?

This plugin will pull all the translations from crowdin and overwrite the existing files. If there are no changes, the files will end up being identical with seemingly no change, but everything is fetched every time. I don't understand how POM dependencies can have any impact, unless of course you somehow want to fetch translations for multiple projects/POMs in one go..?

**Comment by ValentinLorand** [comment]
In fact, I have librairies that defines some translations. I don't want to duplicates theses translations in each projects that depends on these librairies.

And I don't want to retrieve all the translations of my Crowdin project because my Crowdin project is used by ~30 different projects, there are many translations. ^^

The glandais project was able to automatically retrieve all the required translations based on the dependency tree of a Maven project. :)
It's work also for multi-module projects by checking in each module if there are translations to pull.

I hope this answer to your questions

**Comment by Nadahar** [comment]
I've never tested or used this for multi-module/multi-POM projects, so I don't know quite how that would work. I remember that there was something in the original plugin that I didn't quite understand what was for, which was probably related. It probably isn't very complicated to make this work, I just can't do it as long as I don't understand the intended mechanism.

Is any of your projects open-source so that it's possible to get an idea of the POM structure? Or, if not, do you know of any open-source project with a similar structure?

I think it would be nice if this plugin could handle that too, but I can't implement something I don't know how should work. I assume that these different "modules" use different "folders" in Crowdin then? Or, is it just different source files? Also, as I understand you, this plugin will as of now pull all the translations for all the modules regardless of what is needed... which I don't quite understand can mean anything other than that you have defined many `translationFileSet`s?

**Comment by Nadahar** [comment]
Looking at your code, it seems like this probably is "the essentials": https://github.com/ValentinLorand/crowdin-plugin/blob/f852a70f99ca46625e769385dab8e9897132c6f6/src/main/java/com/googlecode/crowdin/maven/mojo/PullCrowdinMojo.java#L73-L80

So, to make that work, `translationFileSet` would need to get a new field `mavenId` and then they would need to be filtered, both for pull and push..? based on the Maven dependency tree?

**Comment by ValentinLorand** [comment]
Yes this part of the code check if the translation should be imported in the project.

Note that my translations of a same project are grouped in Crowdin into folders that are named by the groupId + artefactId of the concerned project. This allows the plugin to detect translations linked that should be imported.
Maybe the system can work with files too but the way of doing this must be studied.

You can find here an example of project using Crowdin here : https://gitlab.inria.fr/gazelle/public/core/test-management/-/tree/develop/gazelle-tm-war/src/main (The crowdin-plugin is in a parent pom.xml, but there is nothing of particular)

My context if a bit particular, that why I preferred to adapt the API instead of using your good solution :)
