### ISSUE TITLE
Not receiving translations

### ISSUE THREAD

**Issue by SubJunk** [DigitalMediaServer/crowdin-maven-plugin#7]
I just ran the command `mvn crowdin:pull -DrootBranch=main` like normal but it only changed `languages.properties`, not the translation files themselves.
I'm not aware of anything changing since I last used this on UMS. Any ideas?

**Comment by SubJunk** [comment]
This was my mistake, there were a lot of updates on Crowdin but none to the server translations, they were all to the knowledge base

**Comment by Nadahar** [comment]
Good, because I wouldn't really have had any idea 😉
